add_newline = false

format = """
$directory\
$git_branch\
$git_status\
$character"""

right_format = """
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$python\
$lua\
$cmd_duration\
"""

[character]
success_symbol = "[❯](bold #ee5396)" 
error_symbol = "[❯](bold #ff7eb6)" 
vimcmd_symbol = "[❮](bold #42be65)"

[directory]
style = "bold #3ddbd9" 
format = "[$path]($style)[$read_only]($style) "
truncation_length = 4
truncation_symbol = "…/"
read_only = " "

[git_branch]
symbol = " "
style = "bold #be95ff"
format = "via [$symbol$branch]($style) "

[git_status]
style = "bold #ff7eb6" 
format = "[$all_status$ahead_behind]($style) "
ahead = " "      
behind = " "     
diverged = " "   
renamed = " "    
deleted = " "    
modified = " "   
staged = " "     
untracked = " "  
conflicted = " " 

[cmd_duration]
min_time = 2000
style = "bold #525252" 
format = "took [$duration]($style) "

[c]
symbol = "C "
style = "bold #33b1ff"

[rust]
symbol = "Rs "
style = "bold #ff7eb6"

[golang]
symbol = "Go "
style = "bold #3ddbd9"

[nodejs]
symbol = "Node "
style = "bold #42be65" 

[php]
symbol = "Php "
style = "bold #be95ff"

[java]
symbol = "Java "
style = "bold #ff7eb6"

[python]
symbol = "Py "
style = "bold #ffe97b"

[lua]
symbol = "Lua "
style = "bold #33b1ff" 

[username]
disabled = true

[hostname]
disabled = true

[os]
disabled = true

[package]
disabled = true 
